name: On merge into main

on:
  push:
    branches:
      - 'main'
    paths-ignore:
      - '**.md'
      - '**.adoc'
      - '**/.gitignore'
      - './github/**'
      - '!./github/workflow/feature-merged.yml'

jobs:
  snapshot:
    runs-on: ubuntu-latest
    steps:
      - name: Install packages
        run: |
          sudo apt update
          sudo apt install -y git
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Get sv4git
        run: |
          wget -O /tmp/sv4git.zip https://github.com/bvieira/sv4git/releases/download/v2.4.0/git-sv_2.4.0_linux_amd64.tar.gz
          cd /usr/local/bin
          tar xzf /tmp/sv4git.zip
          chmod +x git-sv
      - name: Get Version
        id: get-version
        run: |
          VERSION="$(git sv next-version)-SNAPSHOT-$(git rev-parse --short HEAD)"
          echo "VERSION=$VERSION"
          echo "::set-output name=version::$VERSION"
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build and publish to maven central snapshots
        run: ./gradlew publishAllPublicationsToOss -Pversion=${{steps.get-version.outputs.version}}
        env:
          SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
          SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
          GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
          GPG_PRIVATE_PASSWORD: ${{ secrets.GPG_PRIVATE_PASSWORD }}
